### ISSUE TITLE
FFZ and 7TV Channel emotes not available on certain channels

### ISSUE THREAD

**Issue by keineahnungking** [tommyxchow/frosty#115]
The FFZ and 7TV channel emotes are not displayed on some channels. I'm on iOS if that matters. For example on xQc or Northernlion's stream I'm seeing OMEGALUL in the chat and only global FFZ/7TV emotes are displayed in the emote picker.

**Comment by tommyxchow** [comment]
I'm not too sure about Northernlion (it doesn't seem like he has FFZ or 7TV emotes enabled) but xQc recently changed his channel name from xQcOW to just xQc. The current implementation of the emotes from FFZ and 7TV relies on querying the channel name, but it seems like the emote APIs haven't been updated yet for xQc:

Before: https://api.frankerfacez.com/v1/room/xqcow
After: https://api.frankerfacez.com/v1/room/xqc (returns 404 error)


It _may_ end up fixing itself within the next few days (I don't know exactly how their APIs update). Regardless, I'll update the API requests in the app to query for the channel's ID rather than the name so that this doesn't happen again in the future.
