### ISSUE TITLE
Transparent chat fullscreen overlay

### ISSUE THREAD

**Issue by keineahnungking** [tommyxchow/frosty#116]
Right now there is no way to display chat in fullscreen mode and in theater mode the stream is quite small. I'm thinking of a Fullscreen Overlay like the FFZ addon or some Chrome Extensions. Alternatively an option to resize the make the chat width smaller would be nice.

**Comment by humphreyyy** [comment]
yea the chat takes up a lot of space atm. would be great if you could make it smaller

**Comment by tommyxchow** [comment]
> yea the chat takes up a lot of space atm. would be great if you could make it smaller 

I recently implemented an option that lets you resize the chat between 20-80% of the screen size. It'll be arriving in the next update soon:

https://user-images.githubusercontent.com/54859075/170380831-908f45e1-4129-41b4-8d0e-c7c412b30b4f.MOV

**Comment by humphreyyy** [comment]
> > yea the chat takes up a lot of space atm. would be great if you could make it smaller
> 
> I recently implemented an option that lets you resize the chat between 20-80% of the screen size. It'll be arriving in the next update soon:
> 
>  Upload.from.GitHub.for.iOS.MOV

amazing! thank you so much

**Comment by jonathanluepfert** [comment]
First of all, thanks for adding the overlay. The option of a chat on the left side is also great for streamers with top right cams. Right now the chat overlay makes the chat very hard to read because there is no transparent background (see picture for an example). Please add this preferably with options to increase or decrease the transparency.
![17A97111-13F9-48DB-B1C1-3C8716A753DE](https://user-images.githubusercontent.com/57803550/170883303-2467477e-64e2-47e6-99d5-102a9f0be997.png)
