### ISSUE TITLE
[Feature request] Android TV optimization

### ISSUE THREAD

**Issue by AlexeyArtemev** [tommyxchow/frosty#126]
**Request**
Is it possible to optimize the app for android TV use?
Current Android TV troubles:
- Can't open settings tab
- Can't get to the search button from the main screen(it only scrolls down to the "recommended streams" bottomless pit)
- There's an invisible round button on the right of the "categories" button

**Platform info**
- Device: Hi VHIX-43U169MSS(MTK7332, same as MTK9632, armv7l)
- OS: Salyut TV(fork of Android TV v.9, API v.28, kernel 4.9.118+)

**Screenshots**
Invisible button + overall app view from the TV perspective
![image](https://user-images.githubusercontent.com/53113374/170476117-1143befe-0469-42cf-b5f5-074400f10a3d.png)

**Additional info**
I would be happy to help if needed, if so - contact me whenever you want

**Comment by tommyxchow** [comment]
Thank you for bringing this up. I've honestly never realized the app could work on Android TV and never tried it.

Sadly, there is no official Flutter support for Android TV, which is why most elements aren't navigatable. I could probably do some workarounds to make it semi-functional, but I'd also have to refactor many portions of the UI in order to work with the remotes/d-pad navigation.

Since my priority is mobile, I don't see this happening anytime in the near future. I'll leave the issue open if I attempt it in the future or if anyone else wants to give it a shot.

**Comment by tommyxchow** [comment]
Closing this as Flutter's support for Android TV is pretty much nonexistent, so I don't expect it to be accomplished.
