### ISSUE TITLE
Add transparent background to fullscreen chat overlay

### ISSUE THREAD

**Issue by keineahnungking** [tommyxchow/frosty#130]
First of all, thanks for adding the overlay. The option of a chat on the left side is also great for streamers with top right cams. Right now the chat overlay makes the chat very hard to read because there is no transparent background (see picture for an example). Please add this preferably with options to increase or decrease the transparency.
![89526CAB-C775-445B-B294-1FCF39490FFB](https://user-images.githubusercontent.com/105888328/170883444-4a642085-51ea-481c-ad4b-e0686bcd208e.png)

**Comment by tommyxchow** [comment]
I'll work on this next and add it ASAP. I sadly overlooked this due to shifting focus on other things and decided to ship it as-is (not the best idea but oh well).

The plan is to have a semi-transparent background option with adjustments as you said. I'll also see if I can add an additional option with no background and a stroke/outline for text so that text should be readable even without the background.
