### ISSUE TITLE
(Bug) Clicking on an offline users' "visit channel" button doesn't do anything

### ISSUE THREAD

**Issue by ars4l4n** [tommyxchow/frosty#131]
I've had the issue on the most recent app build as well as a previous one.
Android 10, Google Pixel 3

**Comment by tommyxchow** [comment]
This is intentional to prevent misclicks and redirects when interacting with the Twitch web overlay. Clicking on the "visit channel" button will bring you to the web version of the channel as seen below. If this is what you expect to happen, let me know and I can add it in the next update.

![image](https://user-images.githubusercontent.com/54859075/170900253-e5e91252-842e-4a87-9feb-0723c2ed4f88.png)
