### ISSUE TITLE
Button to rotate to landscape

### ISSUE THREAD

**Issue by mmattbtw** [tommyxchow/frosty#138]
**Is your feature request related to a problem? Please describe.**
I usually have rotation lock enabled on my phone 24/7, so I just use app's built in rotation button to rotate to landscape.

**Describe the solution you'd like**
A button on the player to rotate the app into landscape (and back into portrait)

**Comment by tommyxchow** [comment]
I initially didn't have this implemented because there were some limitations with how Flutter handles rotations (it doesn't use actual data from the device sensor). After working on the rotate button and performing some workarounds, the limitations aren't as severe as I recall but there are some things worth mentioning for future reference:

On iOS, based on my limited testing, the rotate button pretty much works identical to how the official Twitch app functions.

On iPads, the button won't show up (just like on the official Twitch app) because I'd have to disable the iPad's multitasking features for it to work. This is because limiting the app to a single orientation will prevent the multitasking feature from functioning correctly. More about that [here](https://api.flutter.dev/flutter/services/SystemChrome/setPreferredOrientations.html) and [here](https://github.com/flutter/flutter/issues/27235#issuecomment-530726236).

Meanwhile, on Android, one caveat is that pressing the rotate button will "lock" the app into landscape mode (i.e., you can't rotate back to portrait mode again unless you tap the rotate button again or navigate back). This is an unfortunate and relatively minor side effect that I couldn't figure out.

Regardless, the feature is pretty much good to go. I'll do a little cleanup if necessary and ship it in the next update.
