### ISSUE TITLE
Animated emotes are sometimes layered ontop of the first frame of the animation

### ISSUE THREAD

**Issue by Icoryx** [tommyxchow/frosty#153]
**Describe the bug**
On some animated emotes you can see the first frame of the animation through the emote like here:
![Screenshot_2022-07-04-23-10-10-09_1f6a23d21ed6c97d5400a99f48294dc8](https://user-images.githubusercontent.com/17325607/177216769-71b3c653-2def-4d56-8727-d7c9fdab802f.jpg)

**To Reproduce**
1. Go into any stream with animated emotes.
2. Look at them. 

**Expected behavior**
The emote should probably not look like this. 

**Screenshots**
See under description. 

**Smartphone (please complete the following information):**
 - Device: OnePlus 8T
 - OS: Android 12
 - App Version: 1.5.0 (24)

**Additional context**

**Comment by tommyxchow** [comment]
I've had this problem with animated emote GIFs ever since I started working on the app and I'm pretty sure it's one of those odd behaviors caused by the Flutter engine. Some GIFs will also play really fast (#1). Creating a fresh Flutter project and putting the GIF there will yield the same results as well.

I'm honestly a bit clueless about how the rendering of GIFs works behind the scenes, so I probably won't be able to fix this one on my own. Since Google and the contributors are the ones working on the Flutter engine, we'll have to wait until they provide a fix.
