### ISSUE TITLE
PiP-Mode would be a great addition

### ISSUE THREAD

**Issue by Icoryx** [tommyxchow/frosty#154]
**Is your feature request related to a problem? Please describe.**
In the normal Twitchapp you can exit and watch any stream you had opened before in Picture-in-picture mode, while doing something else in another app. This is the only thing I'm missing from the normal twitch app and the only reason I still sometimes use it. 

**Describe the solution you'd like**
If you exit the app while watching a stream the stream automatically goes into PiP-mode. You should be able to drag it around, pinch it to make the player bigger or smaller and maybe also a button to pause/play and get back into the app. 

**Describe alternatives you've considered**
I sometimes just use the splitscreen function from android. It's not very good for alot of things tho as some apps don't support this and others which support it get way too small to properly use them. 

**Additional context**
Example:
![Screenshot_2022-07-04-23-19-35-27_f56d448df78e8512261d4bfbcb3978c7](https://user-images.githubusercontent.com/17325607/177217491-fd8610f7-1258-4968-98ef-17186f7a9ca6.jpg)

**Comment by Icoryx** [comment]
Didn't see the headsup about PiP

**Comment by tommyxchow** [comment]
Reopening this issue as I managed to get PiP working on Android thanks to a neat little package ([source](https://pub.dev/packages/floating/example)).

Gonna do some more tests to make sure this is the best solution, but so far things are looking good. I'll also see if I can get the in-app PiP working as well so that we can browse other streams while watching.

[pip-demo.webm](https://user-images.githubusercontent.com/54859075/180861870-f4266045-3387-48d1-be01-573aca42388b.webm)

**Comment by Icoryx** [comment]
Looks promising PagMan

**Comment by tommyxchow** [comment]
Added in v2.1.0 (#164)
