### ISSUE TITLE
Frosty doesn't register that I've signed into my Twitch account.

### ISSUE THREAD

**Issue by Nightbre** [tommyxchow/frosty#169]
**Describe the bug**
I don't actually know if this is a bug, or if it's literally just my phone being its usual self, but for some reason, when I go to sign into my Twitch account, the app doesn't seem to register that I've input the details and authorized it to use my account.

**To Reproduce**
This one... This one I'm not finding any way of replicating, either because the app becomes unresponsive and I have to clear the storage, or because many features simply stop responding. The app doesn't seem to register that anything's even happened, either, which is definitely problematic! I'm new to the app, and there may still be a way to replicate this issue, and I'm simply not seeing it, however.

**Expected behavior**
This is probably a lil' obvious by this point, but simply signing into my Twitch account.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: T-Mobile Revvl 5G
 - OS: Android 11
 - App Version: Version 2.0.0 (25)

**Additional context**
So the real interesting thing is that I can go through the login process like normal, but the moment I tap "authorize" and it goes through to the next screen, it simply blips out of that screen and returns to the app's interface, behaving as if I were still anonymous, but with many of the app's features becoming unresponsive to input, such as the search function and options to change chat behavior. Outside of this change in behavior, the appearance of the interface doesn't change at all.

Clearing the app's storage and uninstalling both net the same results, allowing me to get past the loading screen and into the app, but still behaving as described above when I attempt to sign in.

This could very easily be an issue with the phone I'm using, rather than the app itself, as this sort of thing HAS happened before, but I find it a bit peculiar that it's happening with this app in particular.

**Comment by Nightbre** [comment]
Any help would

**Comment by Nightbre** [comment]
Did I just close this just now-

**Comment by Nightbre** [comment]
Okay wow, I have a lot to learn about this site, it seems. HAHA!

Anyways, any help would be greatly appreciated! I'll edit the main post if I figure out a way to replicate the bug, but it's just *weird*.

**Comment by tommyxchow** [comment]
Thanks for opening this issue. I *might* have an idea of what's causing the login problem.

Frosty currently has [Auto Backup](https://developer.android.com/guide/topics/data/autobackup#EnablingAutoBackup) enabled (it's enabled by default for all Android apps). Auto Backup essentially securely backups up all the settings and user authentication details so that they persist when re-installing the app. This is supposed to make it easier to reinstall apps because you won't have to log in again and tweak all your settings.

I completely forgot about it being enabled until today when I looked over some documentation from [flutter_secure_storage](https://pub.dev/packages/flutter_secure_storage), the package I use to encrypt and store user login tokens on the device itself.

So, when Frosty is reinstalled, it'll restore old existing data which may cause all sorts of issues and conflicts. My code is written in a way that it expects a clean slate when reinstalling. I definitely could've written some better code to handle this situation, but unfortunately, I overlooked it.

To fix this, I'm going to disable Auto Backup on the app. In the future, I may fix up the initialization code so that Auto Backup can be safely re-enabled. 


**One more thing:** If you're familiar with APKs, could you try installing the [Frosty APK here](https://github.com/tommyxchow/frosty/releases/tag/v2.1.0) under "assets" and let me know if that works for you? APKs don't have any backups whatsoever so I want to see if that's the root cause of your case.

**Comment by Nightbre** [comment]
I installed Frosty via the APK and that doesn't seem to be the issue. Same behavior as before, for the most part. I'm unsure as to what may be causing this strange issue.

The biggest difference between the Google Play and APK download is that the app's features continue to respond, but it otherwise still freezes on the startup screen when trying to load back into it.

Attempting to sign in after the first attempt shows the authorization screen, but doesn't change anything if I repeat the process.

**Comment by tommyxchow** [comment]
> I installed Frosty via the APK and that doesn't seem to be the issue. Same behavior as before, for the most part. I'm unsure as to what may be causing this strange issue.
> 
> The biggest difference between the Google Play and APK download is that the app's features continue to respond, but it otherwise still freezes on the startup screen when trying to load back into it.
> 
> Attempting to sign in after the first attempt shows the authorization screen, but doesn't change anything if I repeat the process.
> 
> Edit: Okay, so attempting to sign in without leaving the app (I have 2FA active on my account) resulted in the Twitch login screen appearing after authorizing the app to use my account, but the app quickly closed the window and nothing else changed. It seems it might be something to do with the browser the app pulls up to sign in, if that's what it is.

I'm struggling to understand what the underlying cause could be. The unresponsiveness you mentioned earlier is extremely odd behavior. It's really unfortunate that I'm unable to reproduce this behavior across any of my devices or emulators.

Do you happen to have any extra devices (iOS or Android) by chance? Testing on a different device could probably let us know if the device itself is causing the problem.

Unless another similar case pops up, I can only assume that there must be some rare incompatibility issue with your device in particular.

**Comment by Nightbre** [comment]
I *DO* have other devices, but I'll have to dig one out in order to test this. I'll update you once I do this!

This isn't the first time I've had a weird issue with an app simply not wanting to run on this particular phone, when it would work for literally everybody else, so it wouldn't be surprising if it was literally just my device behaving in weird ways. When this happens, the app in question will *eventually* work, but it could be months before it does.

The T-Mobile Revvl 5G is...not a good phone by any means, and has lots of flaws, but I *do* plan on upgrading it, hopefully soon-ish, so even if I *can't* find a phone to test the app on, I should be able to within the next...month. That is a fairly long wait, however, and I'd much rather not resort to doing this, if it can be avoided.

Sometimes, technology has a way of simply not working as intended.

Stay tuned for updates!

**Comment by Nightbre** [comment]
Okay, so I've tested the app on an older device (Android 9) and the same issue occurred.

I'm unsure exactly what the root cause of this issue could be, if it's not my phone itself... It could very easily be linked to my Twitch account, but that doesn't make any sense.

*Maybe* it could have something to do with the 2FA on my Twitch account, but again, it doesn't make much sense to me.

**Comment by tommyxchow** [comment]
> Okay, so I've tested the app on an older device (Android 9) and the same issue occurred.
> 
> I'm unsure exactly what the root cause of this issue could be, if it's not my phone itself... It could very easily be linked to my Twitch account, but that doesn't make any sense.
> 
> _Maybe_ it could have something to do with the 2FA on my Twitch account, but again, it doesn't make much sense to me.
> 
> Edit: Well _that_ didn't do anything other than disconnect me from literally everything. This is indeed a very strange issue.

Yeah, looks like it's probably not your device causing the problem for Frosty. Perhaps it's something bugging out when Frosty obtains and parses the account information.

I hate to ask again, but do you happen to have a second Twitch account you can try logging in with as well? It'll tell us if there's something related to your account specifically that may be causing the issue (it's a bit of a reach, but worth a try).

Regardless, I really appreciate you taking the time and cooperating. Login issues are particularly hard to debug since I can't just ask for someone's credentials. Hopefully, I can get to the bottom of this.

**Comment by Nightbre** [comment]
> > Okay, so I've tested the app on an older device (Android 9) and the same issue occurred.
> > I'm unsure exactly what the root cause of this issue could be, if it's not my phone itself... It could very easily be linked to my Twitch account, but that doesn't make any sense.
> > _Maybe_ it could have something to do with the 2FA on my Twitch account, but again, it doesn't make much sense to me.
> > Edit: Well _that_ didn't do anything other than disconnect me from literally everything. This is indeed a very strange issue.
> 
> Yeah, looks like it's probably not your device causing the problem for Frosty. Perhaps it's something bugging out when Frosty obtains and parses the account information.
> 
> I hate to ask again, but do you happen to have a second Twitch account you can try logging in with as well? It'll tell us if there's something related to your account specifically that may be causing the issue (it's a bit of a reach, but worth a try).
> 
> Regardless, I really appreciate you taking the time and cooperating. Login issues are particularly hard to debug since I can't just ask for someone's credentials. Hopefully, I can get to the bottom of this.

It's not a problem at all! I know with enough time and patience, we'll be able to get this figured out.

I don't *think* I have a second Twitch account, but I can always make one that's linked to my second Gmail account! I'll do that in the morning, since it's getting late, but maybe it'll give us some insight on what all's going on.

**Comment by Nightbre** [comment]
Okay, so I created a Twitch account using my secondary email account, and tried signing into Frosty with it, to which I was capable, so it must be something to do with my main account.

This is quite bizarre to me, but at least we *kind of* know what's going on. Now to figure out why it's behaving the way that it is!

**Comment by tommyxchow** [comment]
I also have Twitch turbo so it _probably_ isn't the cause. There's a good chance it's caused by some kind of unhandled case in Frosty's code when parsing the account data after logging in.

After you log in, through the publicly available Twitch API, Frosty obtains your
- Twitch id
- Twitch login
- Twitch display name
- Twitch profile image URL
- List of blocked users

I don't believe that the ID or profile image URL is the cause of the problem, so we can cross those out. When parsing the information, there might be some strange characters that can cause the process to fail, so I'd like to ask:
1. For your login/username, are there any weird extraneous characters, or are they all alphanumeric?
2. Do you have any blocked users? If so, is it unusually large? Or are there any crazy-looking names in there?

Also, Twitch may have some different international URLs that I haven't handled. Just to make sure (if you're comfortable sharing) are you based inside or outside the United States?

**Comment by Nightbre** [comment]
> I also have Twitch turbo so it _probably_ isn't the cause. There's a good chance it's caused by some kind of unhandled case in Frosty's code when parsing the account data after logging in.
> 
> After you log in, through the publicly available Twitch API, Frosty obtains your
> 
>     * Twitch id
> 
>     * Twitch login
> 
>     * Twitch display name
> 
>     * Twitch profile image URL
> 
>     * List of blocked users
> 
> 
> I don't believe that the ID or profile image URL is the cause of the problem, so we can cross those out. When parsing the information, there might be some strange characters that can cause the process to fail, so I'd like to ask:
> 
>     1. For your login/username, are there any weird extraneous characters, or are they all alphanumeric?
> 
>     2. Do you have any blocked users? If so, is it unusually large? Or are there any crazy-looking names in there?
> 
> 
> Also, Twitch may have some different international URLs that I haven't handled. Just to make sure (if you're comfortable sharing) are you based inside or outside the United States?

I live in the US, yes, but I have a very suspicious feeling it may have to do with my blocklist.

That could *very* easily be my issue, because I have so many bot accounts on my blocklist that it takes a hot minute to actually load! It could be that it's taking Frosty a good long while to actually process that information, which is causing the issue! I literally *never* thought of that! HAHA!

**Comment by tommyxchow** [comment]
Okay, it's definitely the blocked list then! I never got the chance to test with hundreds/thousands of blocked users because I wasn't aware of any method that could block large amounts of people quickly.

Very interesting bug for sure, I'm going to figure out a way to optimize the process of obtaining all the blocked users later tonight/tomorrow!

**Comment by Nightbre** [comment]
> Okay, it's definitely the blocked list then! I never got the chance to test with hundreds/thousands of blocked users because I wasn't aware of any method that could block large amounts of people quickly.
> 
> Very interesting bug for sure, I'm going to figure out a way to optimize the process of obtaining all the blocked users later tonight/tomorrow!

When you mentioned that Frosty pulled your blocklist, I was like "Wait-" because it clicked that I have a very insane amount of accounts blocked!

I may try signing into Frosty and simply letting it sit for a good while to see what happens. Could be nothing, but it might eventually sign me in!

**Comment by tommyxchow** [comment]
A quick little (late) update: I've made some tweaks that _should_ prevent the process of getting blocked users from halting/lagging the UI. I've uploaded an [APK on Google Drive](https://drive.google.com/file/d/1Y_b73eT_defiPkMv9AZp6L48FA7ZDNCN/view?usp=sharing) that you can try (couldn't upload it here on GitHub due to size limitations), please let me know if it's improved or fixed!

**Comment by Nightbre** [comment]
> A quick little (late) update: I've made some tweaks that _should_ prevent the process of getting blocked users from halting/lagging the UI. I've uploaded an [APK on Google Drive](https://drive.google.com/file/d/1Y_b73eT_defiPkMv9AZp6L48FA7ZDNCN/view?usp=sharing) that you can try (couldn't upload it here on GitHub due to size limitations), please let me know if it's improved or fixed!

Ah, it worked! I signed in without an issue! Went straight back to the interface and showed I was properly signed in!

**Comment by tommyxchow** [comment]
> Ah, it worked! I signed in without an issue! Went straight back to the interface and showed I was properly signed in!

Phew! That's relieving to hear. I'll have the changes in the next update soon, you can use the APK in the meanwhile.

Thank you so much again for your time and cooperation (and the donation! <3). This was a satisfying bug fix, and I absolutely would not have known or even fixed it had you not brought it up and provided the crucial details.

**Comment by Nightbre** [comment]
> > Ah, it worked! I signed in without an issue! Went straight back to the interface and showed I was properly signed in!
> 
> Phew! That's relieving to hear. I'll have the changes in the next update soon, you can use the APK in the meanwhile.
> 
> Thank you so much again for your time and cooperation (and the donation! <3). This was a satisfying bug fix, and I absolutely would not have known or even fixed it had you not brought it up and provided the crucial details.

Not a problem! I figured that since it was an issue I was having, others would likely be having the same issue and wanted to try and help get it figured out, so I'm glad we were able to piece things together and get it resolved!
