### ISSUE TITLE
Possibility to move the three dots that open the list of chatters 

### ISSUE THREAD

**Issue by erikholmes564** [tommyxchow/frosty#173]
**Is your feature request related to a problem? Please describe.**
This is about the three dots at the bottom right of the screen, I keep pressing on it involuntarily when trying to see emotes and it gets a bit annoying.

**Describe the solution you'd like**
Two solutions I thought of:
- option to move the three dots above the screen where settings wheel cog is
- option to hide it completely 

I know this is a very minor thing but I thing it would be a good QoL change. 
(See attached screenshot) 
![1C3AFD88-7CFD-4304-974B-6B668637E775](https://user-images.githubusercontent.com/21347659/182981445-695816b1-85a1-4bdf-aa09-53b84d499bca.jpeg)

**Comment by tommyxchow** [comment]
Thanks for the suggestion, I can see how this is a bit of a problem. I only have it at the bottom right because it's similar to the layout on the official Twitch app.

I think having an option to hide it (like you said) or on the left side would be a good solution.

**Comment by erikholmes564** [comment]
I've never had the same issue with the official app with the 3 dots, maybe it's because the hit boxes are different or it is more distant from the emote button. Either way I hope a solution is found.

**Comment by tommyxchow** [comment]
Hey there, sorry for the late response: I took a small break from Frosty and had to work on some stuff in the backlog.

I've added an option to move the emote menu button to the left side of the text field as seen below:

![Screen Shot 2022-09-06 at 12 27 42 PM](https://user-images.githubusercontent.com/54859075/188687650-a4c8ac72-c627-4261-b92b-387afa956ff6.png)

I thought about moving the three dots to the left side, but I felt it would be too confusing since the send button would end up on the left side as well. Hopefully, this workaround is sufficient.
