### ISSUE TITLE
Stream uptime and PiP when closing app

### ISSUE THREAD

**Issue by TechGeeksIO** [tommyxchow/frosty#198]
First of all, thanks for this great project and your work, I really appreciate it!

I have two feature requests,
- adding stream uptime next to the viewers count
- automatically switch to PiP when closing the app
- Optional: PiP while browsing other streams.

Thank you! Enjoy the coffee 😊

**Comment by IS2511** [comment]
> automatically switch to PiP when closing the app

Would be very appreciated, should be a setting probably, bump

**Comment by zeykafx** [comment]
I added PiP when leaving the app, swipe controls, and Matrerial Design 3 on my fork of the app, I will see if I make a pull request or not because I'm not confident enough in my code 😆

**Comment by tommyxchow** [comment]
Hey, **thank you** for the support and apologies for the (obviously) very late response. I was a bit burnt out from working on Frosty and decided to take a break to focus on other things and regain my motivation.

Anyways - on Android, I've rebuilt the PiP functionality with a [newer package](https://github.com/PuntitOwO/simple_pip_mode_flutter) so that it enters PiP automatically when leaving Frosty. There's also a new play/pause button when in PiP mode.

Unfortunately, on iOS after some trial and error, I believe automatic PiP is not possible yet. Automatic PiP requires a true native video component, but Frosty actually uses a WebView to show streams. This is because Twitch's API doesn't provide actual stream URLs, so I had to resort to using a fullscreen version of the Twitch website instead.

I've also redesigned the video overlay to accommodate the stream uptime.

Here is a demo of everything (note: the smooth gesture transition seen below is [a feature only on Android 12+](https://developer.android.com/develop/ui/views/picture-in-picture#smoother-transition)):

https://user-images.githubusercontent.com/54859075/209741898-37087623-b570-4879-9c52-acca4d5b500d.mp4

As for @zeykafx's fork, there are quite a lot of major changes to go through so I'll have to set it aside until I finish working on my backlog of stuff. Hopefully, I'll find some time in the future to clean up the fork with you and will be able to have the changes merged.
