### ISSUE TITLE
Bypass 720p limit in Korea region.

### ISSUE THREAD

**Issue by Arc-Jung** [tommyxchow/frosty#202]
**Is your feature request related to a problem? Please describe.**
@RoonMoonlight
@tommyxchow 

Starting from September 30 2022, the 720p limitation will apply to Twitch with Korea region, which is very annoying.
Is there any ways to bypass this limit, please add that feature.

Related article:
https://twitter.com/zachbussey/status/1575326770735226880

**Comment by RoonMoonlight** [comment]
Why you mention me

And you just copy pasted my issue, what's wrong with you

https://github.com/crackededed/Xtra/issues/160

I kindly ask you refrain from doing so or I will have to block you, thank you

**Comment by RoonMoonlight** [comment]
I mean making issue is fine, but please do not mention me unless it's important.

**Comment by Arc-Jung** [comment]
@RoonMoonlight 
Okay. i am so sorry. But this application faced same issue. i used your opinion.

**Comment by tommyxchow** [comment]
Hey there, Frosty's player is done through Twitch's mobile website so I don't really have much control over it. For now, I don't plan on implementing TTV LOL either since it would probably result in Twitch taking down Frosty on the app stores.

I'm not familiar with any other ways of circumventing the 720p limit, so if a potential solution comes up in the future feel free to bring it up. For now, I'm going to close this issue, very sorry about this.
