### ISSUE TITLE
I'm getting ad's but I'm subscribed 

### ISSUE THREAD

**Issue by Ijustwannafly7** [tommyxchow/frosty#203]
**Describe the bug**
On twitch I do not get ads but on this I'm signed in to my account which I'm subed yet still receive ads
**To Reproduce**
Everytime I watch a stream
**Expected behavior**
To not see ads with a subed account 
**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 13, Pixel 6]
 - OS: [e.g. iOS 15, Android 12]
 - App Version: [check in Settings -> Other -> About Frosty. e.g. v1.4.1 (22)]
I don't think this has to do with my phone considering I tried it on two different ones
**Additional context**

**Comment by tommyxchow** [comment]
Hey there, apologies for the late response.

The current method of authenticating users to prevent subbed ads is a bit scuffed due to the lack of a better method.

The best thing I can suggest right now is to try to log out/log in again, or if there is some kind of proxy or VPN used on your network, turn it off temporarily and see if the login works correctly - it may be blocking the login from succeeding.

In the next release or two, I'll see if I can implement a new option where you log in and authenticate manually on the WebView if the automated process fails.
